home/urls.py
from django.urls import path
from . import views

app_name="frontview"

urlpatterns = [
    path('',views.homeView,name='homeView'),
    path('hr',views.hrView,name='hrView'),
    path('legal',views.legalView,name='legalView'),
    path('about',views.aboutView,name='aboutView'),
    path('jobs/<str:section>',views.sectionView,name="sectionView"),
    path('<int:article_id>/<slug:article_slug>',views.articleView,name="articleView"),
]

zinagohr/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path,include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('',include("home.urls"),name='home'),
    path('admin/', admin.site.urls),
    path('publisher/',include("publishers.urls")),
    path('applications/',include("application.urls")),
    path('login/',include("login.urls")),
    path('password_reset/',auth_views.PasswordResetView.as_view(template_name="login/passwordreset.html"),name='password_reset',),
    path('password_reset_done/',auth_views.PasswordResetView.as_view(template_name="login/password_reset_done.html"),name="password_reset_done",),
    path('password_reset_confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name="login/password_reset_confirm.html"), name='password_reset_confirm',),
    path( 'password_reset_completed/',auth_views.PasswordResetCompleteView.as_view(template_name="login/password_reset_complete.html"), name='password_reset_complete',),
]

urlpatterns+=staticfiles_urlpatterns()

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

publishers/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import pre_save, post_delete
from django.dispatch import receiver
# from django.utils import timezone
import datetime
import re
from PIL import Image
from math import floor
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile
import sys
# Create your models here.


class Section(models.Model):
    Name = models.CharField("Name", max_length=156)
    description = models.TextField(default="null", blank=False)

    def __str__(self):
        return self.Name

    class Meta:
        managed = True
        verbose_name = 'Section'
        verbose_name_plural = 'Sections'


class Publisher(models.Model):
    account = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name="Account")
    first_name = models.CharField("First Name", max_length=156)
    last_name = models.CharField("Last Name", max_length=156)
    verified = models.BooleanField(default=False)
    description = models.TextField("description", max_length=150, null=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    class Meta:
        managed = True
        verbose_name = 'Publisher'
        verbose_name_plural = 'Publishers'


class Article(models.Model):
    section = models.ForeignKey(Section, on_delete=models.CASCADE,related_name="section_article")
    title = models.CharField(max_length=255)
    title_slug = models.SlugField(default="null")
    description = models.TextField()
    keywords = models.CharField(max_length=255, default="null")
    image = models.ImageField(null=True,blank=True)
    image_source = models.CharField(max_length=255, null=True, blank=True)
    image_description = models.CharField(
        max_length=255, default='image', blank=True)
    sub_heading = models.CharField(max_length=255, null=True, blank=True)
    body_text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    mod_date = models.DateTimeField(null=True)
    publisher = models.ManyToManyField(Publisher)
    view_count = models.IntegerField(default=0)
    publish = models.BooleanField(default=False)
    still_open = models.BooleanField(default=True)

    def bodySnippet(self):
        body = self.body_text[:120]
        bodySnippet = re.sub(
            r"\s\w+$|(<strong>|</strong>|<em>|</em>|<b>|</b>|<i>|</i>|<u>|</u>|<a.+?>|</a>)", "", body)
        return f'{bodySnippet} ....'

    def __str__(self):
        return self.title

    class Meta:
        managed = True
        verbose_name = 'Article'
        verbose_name_plural = 'Articles'
        ordering = ['-pub_date']

    # def delete(self, *args, **kwargs):
    #     self.image.delete()
    #     super().delete(*args, **kwargs)

    def save(self, skip_md=True, *args, **kwargs):
        if skip_md:
            self.mod_date = datetime.datetime.now()
            
   

        if self.image:
            target_height = 333
            im = Image.open(self.image)
            width,height=im.size
            output = BytesIO()
            newHeight= target_height
            newWidth= int(newHeight/height*width)
            im = im.resize((newWidth,newHeight))
            im.save(output, format='JPEG', quality=100)
            output.seek(0)
            self.image = InMemoryUploadedFile(output, 'ImageField', "%s.jpg" % self.image.name.split(
                    '.')[0], 'image/jpeg', sys.getsizeof(output), None)

        super().save(*args, **kwargs)  # Call the real save() method


class Sections(models.Model):
    """Model definition for Sections."""
    # TODO: Define fields here
    article = models.ForeignKey(
        Article, related_name='sections', on_delete=models.CASCADE)
    sub_heading = models.CharField(max_length=255, null=True)
    Sub_section_image = models.ImageField(null=True, blank=True)
    image_source = models.CharField(max_length=255, null=True, blank=True)
    image_description = models.CharField(
        max_length=255, default="image", blank=True)
    body_text = models.TextField(null=True)

    class Meta:
        """Meta definition for Sections."""
        verbose_name = 'Sections'
        verbose_name_plural = 'Sections'

    def __str__(self):
        """Unicode representation of Sections."""
        return self.sub_heading

    def save(self, *args, **kwargs):
        if self.Sub_section_image:
            im = Image.open(self.Sub_section_image)
            width, height = im.size
            output = BytesIO()
            n = 0.5
            Width = floor(width * n)
            Height = floor(height * n)
            if width > 1000:
                im = im.resize((Width, Height))
                im.save(output, format='JPEG', quality=100)
                output.seek(0)
                self.Sub_section_image = InMemoryUploadedFile(output, 'ImageField', "%s.jpg" % self.Sub_section_image.name.split('.')[
                                                              0], 'image/jpeg', sys.getsizeof(output), None)

        super().save(*args, **kwargs)  # Call the real save() method

    # def delete(self, *args, **kwargs):
    #     self.Sub_section_image.delete()
    #     super().delete(*args, **kwargs)


@receiver(pre_save, sender=Article)
def delete_Artictle_image(sender, instance, *args, **kwargs):
    if instance.pk:
        article = Article.objects.get(pk=instance.pk)
        if article.image != instance.image:
            article.image.delete(False)


@receiver(pre_save, sender=Sections)
def delete_Sections_image(sender, instance, *args, **kwargs):
    if instance.pk:
        section = Sections.objects.get(pk=instance.pk)
        if section.Sub_section_image != instance.Sub_section_image:
            section.Sub_section_image.delete(False)


@receiver(post_delete, sender=Article)
def delete_artictle_image(sender, instance, using, *args, **kwargs):
    if instance.image:
        instance.image.delete(save=False)


@receiver(post_delete, sender=Sections)
def delete_sections_image(sender, instance, using, *args, **kwargs):
    if instance.Sub_section_image:
        instance.Sub_section_image.delete(save=False)

home/views.py
from django.shortcuts import render, reverse
from django.http import  HttpResponseRedirect
from publishers.models import Section, Article, Sections
from application.form import application_form

# Create your views here.
def homeView(request):
    return render(request,'home/index.html')

def hrView(request):
    return render(request,'home/hr.html')

def legalView(request):
    return render(request,'home/legal.html')

def aboutView(request):
    return render(request,'home/about.html')

def articleView(request, article_id, article_slug):
    article = None
    try:
        article = Article.objects.get(id=article_id)
    except Article.DoesNotExist:
        return HttpResponseRedirect(reverse('frontview:homeView',
            kwargs={}))       
    article_sections = Sections.objects.filter(article=article)
    section = Section.objects.get(section_article=article)
    articles = section.section_article.filter(
        publish=True, still_open = True)
    nullvalue = "<p>null</p>" or "null"
    history= "HISTORY"
    article.view_count += 1
    article.save(skip_md=False)
    form = application_form()
    message = None
    mostViewed = Article.objects.filter(section=section).filter(
        publish=True,still_open = True).order_by("-view_count")[:10]
    # articles=Article.objects.filter(section=section)
    if request.method == "POST":
        registeration_form = application_form(
        data=request.POST, files=request.FILES)
        if registeration_form.is_valid():
            registeration_form.save()
            message = "Application submitted successfully."
    if article.title_slug != article_slug:
        return render(request, "home/pagenotfound.html", {
            "sections": article_sections, "section": section,
            'articles':articles,"mostviewed": mostViewed})
    return render(request, "home/articleview.html", {"article": article,"sections": article_sections,
                                                     "section": section, "mostviewed": mostViewed, 
                                                     "nullvalue": nullvalue,"HISTORY":history,
                                                     "registrationForm":form,'message':message,
                                                     'articles':articles})


def sectionView(request, section):
    section = Section.objects.get(Name=section)
    articles = Article.objects.filter(section=section).filter(
        publish=True,still_open = True)
    mostViewed = Article.objects.filter(section=section).filter(
        publish=True,still_open = True).order_by("-view_count")[:10]
    return render(request, "home/sectionView.html", {"section": section,'articles':articles,
                                                     "mostviewed": mostViewed})

home/templates/home/articleview.html
{% extends 'home/homeview.html' %} {% block meta_tags %} {% load static %}
<title>ILLUMEPEDIA</title>
<meta name="description" content="{{article.description}}" />
<meta name="keywords" content="{{article.keywords}}" /> {% for publisher in article.publisher.all %}
<meta name="author" content="{{publisher}}" /> {% endfor %}
<meta property="og:url" content="{{request.build_absolute_uri}}" />
<meta property="og:type" content="article" />
<meta property="og:title" content="{{article.title}}" />
<meta property="og:description" content="{{article.description}}" /> {% endblock meta_tags %} {% block sideNav %} {% if articles %}
<h3 id=""><a href="{% url 'frontview:sectionView' section %}">
    {{section}} Job Posts</a></h3>
<input type="text" id="SearchInput" onkeyup="SearchFunction()" placeholder="Search posts" id="myInput">
<ul id="sideNavUL">
    {% for article in articles %}
    <li><a class="a" href="{% url 'frontview:articleView' article.id article.title_slug %}">{{article}}</a></li>
    {% endfor %}
</ul>
{% else %}
<h3 id="">{{section}} Job Posts</h3>
<p>No vacancies at the moment</p>
{% endif %} {% endblock sideNav %} {% block mainHeading %}
<div id="mainhead" class="mainhead">
    <h2 id="mainHeading">{{article.title}}</h2>
</div>
{% endblock mainHeading %} {% block main %}
<section class="articleBox">
    <div id="fb-root"></div>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v5.0"></script>
    <script>
        (function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s);
            js.id = id;
            js.src = "https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.0";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>
    <script>
        window.twttr = (function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0],
                t = window.twttr || {};
            if (d.getElementById(id)) return t;
            js = d.createElement(s);
            js.id = id;
            js.src = "https://platform.twitter.com/widgets.js";
            fjs.parentNode.insertBefore(js, fjs);

            t._e = [];
            t.ready = function(f) {
                t._e.push(f);
            };

            return t;
        }(document, "script", "twitter-wjs"));
    </script>
    <article class="article">
        {% if article.image %}
        <div class="imgcontainer">
            <figure class="">
                <img src="{{article.image.url}}" alt="{{article.image_description}}">
                <figcaption><em>Image Source: {{article.image_source}}</em></figcaption>
            </figure>
        </div>
        <div class="share">
            <div class="fb-share-button" data-href="{{request.build_absolute_uri}}" data-layout="button_count" data-size="small">
            </div>
            <a class="twitter-share-button" href="https://twitter.com/intent/tweet?text={{article.description}}" data-size="">
                <img id="twitter icon" src="{% static 'css/social/twitter.png' %}" alt="">
            </a>
            <a href="whatsapp://send?text={{request.build_absolute_uri}}"> <img id="whatsappicon" src="{% static 'css/social/whatsapp.png' %}" alt=""></a>
            <div style="display:inline ;" class="fb-share-button" data-href="{{request.build_absolute_uri}}" data-layout="button_count" data-size="small">
                <a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u={{request.build_absolute_uri}}&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore"><img id="facebook icon" src="{% static 'css/social/facebook.png' %}" alt=""></a>
            </div>
        </div>
        {% endif %}


        <section>
            {% if article.sub_heading %}
            <h3 class="">{{article.sub_heading}}</h3>
            {% endif %} {{article.body_text|safe}}
        </section>
        {% for section in sections %}
        <section>
            <h3>{{section.sub_heading}}</h3>
            {% if section.Sub_section_image %}
            <figure style="margin-bottom: 10px;" class="">
                <img src="{{section.Sub_section_image.url}}" alt="{{section.image_description}}">
                <figcaption><em>Image Source: {{section.image_source}}</em></figcaption>
            </figure>{% endif %} {{section.body_text|safe}}
        </section>
        {% endfor %}

        <p class="pub_date">{{article.mod_date}}</p>

        <div class="share">
            <div class="fb-share-button" data-href="{{request.build_absolute_uri}}" data-layout="button_count" data-size="small">
            </div>
            <a class="twitter-share-button" href="https://twitter.com/intent/tweet?text={{article.description}}" data-size="">
                <img id="twitter icon" src="{% static 'css/social/twitter.png' %}" alt=""></a>
            <a href="whatsapp://send?text={{request.build_absolute_uri}}"> <img id="whatsappicon" src="{% static 'css/social/whatsapp.png' %}" alt=""></a>
            <div style="display:inline ;" class="fb-share-button" data-href="{{request.build_absolute_uri}}" data-layout="button_count" data-size="small">
                <a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u={{request.build_absolute_uri}}&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore"><img id="facebook icon" src="{% static 'css/social/facebook.png' %}" alt=""></a>
            </div>
        </div>

</section>
{% if article.still_open %}
<form id="apply" action="{% url 'frontview:articleView' article.id article.title_slug %}" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    <legend>Application Form</legend>
    <div class="form_body">
        {{registrationForm}}
    </div>

    <button type="submit" class="submitButton">Apply</button>
</form>
{% else %}
<p>Application Closed</p>
{% endif %}


</article>


{% endblock main %} {% block ads %} {% endblock ads %} {% block mostviewed %} {% if mostviewed %}
<h2>Most Viewed Job Posts</h2>
<div id="" class="articleInnerBox">

    {% for article in mostviewed %}
    <section class="articleDisplayBox">
        <h3><a href="{% url 'frontview:articleView' article.id article.title_slug %}">{{article}}</a></h3>
        <!-- {% if article.image %}
        <img class="" src="{{article.image.url}}" alt="{{article.image_description}}">{% endif %} -->
        <p>{{article.bodySnippet|safe}}</p>
        <p class="pub_date"> {{article.mod_date}}</p>
    </section>
    {% endfor %}
</div>
{% endif %} {% if message %}
<script>
    alert("{{message}}")
</script>
{% endif %} {% endblock mostviewed %} {% block news %} {% endblock news %}

home/templates/home/dropdown.html
<section id="dropdown">
    <a href="javascript:void(0)" onclick="showNot()" id="close" class="close">&times;</a> {% comment %}
    <div id="1_" class="drops navdiv">
        <a class="link" href="#">Services</a>
        <div class="dropdown_1">
            <a class="link" href="{% url 'frontview:legalView' %}">Legal</a>
            <a class="link" href="{% url 'frontview:hrView' %}">Human Resource</a>
        </div>
    </div> {% endcomment %} {% if sorted_sections %}
    <div id="2_" class="drops navdiv">
        <a class="link" href="#">Jobs</a>
        <div class="dropdown_2">
            {% for section in sorted_sections %}
            <a class="link" href="{% url 'frontview:sectionView' section %}">{{section}}</a> {% endfor %}
        </div>
    </div>
    {% endif %}
    <div class="navdiv">
        <a class="link" onclick="showNot()" href="#contact">Contact</a>
    </div>
    <div class="navdiv">
        <a class="link" href="{% url 'frontview:aboutView' %}">About</a>
    </div>
    {% if articles %}
    <div class="dropdown_nav">
        <h3 id="">
            {{section}} Job Posts</h3>
        <input type="text" id="SearchInput2" onkeyup="SearchFunction2()" placeholder="Search posts" id="myInput2">
        <ul id="sideNavUL2">
            {% for article in articles %}
            <li><a class="a" href="{% url 'frontview:articleView' article.id article.title_slug %}">{{article}}</a></li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}
</section>

home/templates/home/homenav.html
{% comment %} <div class="drop gnav">
    <a class="link" href="#">Services</a>
    <div class="dropdown">
        <a class="link" href="{% url 'frontview:legalView' %}">Legal</a>
        <a class="link" href="{% url 'frontview:hrView' %}">Human Resource</a>
    </div>
</div> {% endcomment %}

{% if sorted_sections  %}
<div class="drop2 gnav">
    <a class="link" href="#">Jobs</a>
    <div class="dropdown2">
        {% for section in sorted_sections  %}
        <a class="link" href="{% url 'frontview:sectionView' section %}">{{section}}</a>
    {% endfor %}
    </div>
</div>
{% endif %}
    
<div class='gnav'>
    <a class="link" href="#contact">Contact</a>
</div>

<div class="gnav">
    <a class="link" href="{% url 'frontview:aboutView' %}">About</a>
</div>
<div id="toggle" onclick="show()" class="toggle">
    <span></span>
    <span></span>
    <span class="last"></span>
</div>

home/templates/home/homeview.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@400;500;700&family=Roboto:ital,wght@0,400;0,500;0,700;1,400;1,500;1,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/portal.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/dropdown.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/fonts.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="shortcut icon" href="{% static 'css/img/logo.png' %}" type="image/png">
    <link rel="apple-touch-icon" href="{% static 'css/img/logo.png' %}">
    <link rel="icon" href="{% static 'css/img/logo.png' %}" type="image/png"> {% block title %}
    <title>Portal | Zinago </title>
    {% endblock title %} {% block meta_tags %}
    <meta name="author" content="Emeka Casper Onwuepe " />
    <meta name="description" content="A Human Resource and legal firm dedicated to providing professional legal and HR Consulting Services and evolving Recruitment Solutions that help our customers become more productive and profitable." /> {% block keywords %}
    <meta name="keywords" content="Consulting, Human Resources, Recruitment,law firm, Abuja, Abuja law firm, Services" /> {% endblock keywords %}
    <meta name="author" content="Emeka Casper Onwuepe " />
    <meta property="og:url" content="{{request.build_absolute_uri}}" />
    <meta property="og:type" content="service" />
    <meta property="og:title" content="Zinago HR and Legal Services" />
    <meta property="og:description" content="A Human Resource firm dedicated to providing professional HR Consulting Services and evolving Recruitment Solutions that help our customers become more productive and profitable." />{% endblock meta_tags %}
</head>

<body>
    <div class="bigwrapper">
        <header>
            <section class="logo">
                <a href="{% url 'frontview:homeView' %}"> <img class="logo" src="{% static 'css/img/logo.png' %}" alt="logo"></a>
            </section>
            <nav>
             {% include './homenav.html' %}
            </nav>
            {% include './dropdown.html' %}
        </header>
        <div class="sperator"></div>
        <section id="top" class="banner">
            <div class="bannertext">
                <p class='banner_p1'>Zinago Job Portal</p>
                <p class='banner_p2'>We connect you to amazing unadvertized job opportunities.</p>
            </div>
        </section>
        <main id="main">
            <div class="wrapper">
                <aside id="sideNav" class="sideNav">
                    <a href="javascript:void(0)" onclick="showNot()" id="close" class="close">&times;</a>
                    <!--p id="demo">hello</p-->
                    {% block sideNav %}
                    <h3 id="">SECTIONS</h3>
                    <ul id="sideNavUL">
                        {% for section in sections %}
                        <li><a class="a" href="{% url 'frontview:sectionView' section %}">{{section}}</a></li>
                        {% endfor%}
                    </ul>
                    {% endblock sideNav %}
                </aside>
                <div class="main">
                    {% block mainHeading %}
                    <div id="mainhead" class="mainhead" style="display: none">
                        <h1 id="mainHeading"></h1>
                    </div>
                    {% endblock mainHeading %} {% block main %}
                    <section class="articleBox">
                        {% for section in sections %}
                        <div id="{{section}}" style="clear:both;background-color: #056fb6">
                            <h2 style="text-align:center; padding:8px 0px">{{section}}</h2>
                            <div class="articleInnerBox">
                                {% for article in section.article_set.all %} {% if article.publish %}
                                <section class="articleDisplayBox">
                                    <h3><a href="{% url 'frontview:articleView' article.id article.title_slug %}">{{article}}</a>
                                    </h3>
                                    <img class="" src="{{article.image.url}}" alt="{{article.image_description}}"> {{article.bodySnippet|safe}}
                                    <p>Published By {% for publisher in article.publisher.all %}
                                        <a href="{% url 'frontview:publisherPage' publisher.id %}">{{publisher}} </a> {% endfor %}
                                    </p>
                                    <p class="pub_date">{{article.mod_date}}</p>
                                </section>
                                {% endif %} {% endfor %}
                            </div>
                        </div>
                        {% endfor %}
                    </section>
                    {% endblock main %}
                </div>
            </div>
            <section class="ads">
                {% block ads %} {% endblock ads %}
            </section>
            <section class="mostViewed">
                {% block mostviewed %}
                <h2>
                    Most Viewed Articles</h2>
                <div id="" class="articleInnerBox">

                    {% for article in mostviewed %} {% if article.publish %}
                    <section class="articleDisplayBox">
                        <h3><a href="{% url 'frontview:articleView' article.id article.title_slug %}">{{article}}</a></h3>
                        <img class="" src="{{article.image.url}}" alt="{{article.image_description}}"> {{article.bodySnippet|safe}}
                        <p>Published By {% for publisher in article.publisher.all %}
                            <a href="{% url 'frontview:publisherPage' publisher.id %}">{{publisher}} </a> {% endfor %}
                        </p>
                        <p class="pub_date">{{article.mod_date}}</p>
                    </section>
                    {% endif %} {% endfor %}
                </div>
                {% endblock mostviewed %}
            </section>
            <section class="ads">
                {% block news %} {% endblock news %}
            </section>
            {% include './contactus.html' %}
            
        </main>

        <div onclick="window.scrollTo({top: 0, behavior:'smooth'})" id="backToTop" class="backToTop">
            <a onclick="window.scrollTo({top: 0, behavior:'smooth'})">&#10094;</a>
        </div>
        
            {% block footer %}
            <footer>
                <p id="footer"> Copyright &copy;
                    <span id="footerdate" style="padding: 0%"></span>. All rights reserved. www.zinago.ng
                </p>
            </footer>
            {% endblock footer %}
    
    </div>
    <script src="{% static 'javascript/articleview.js' %}"></script>
</body>

</html>

home/templates/home/pagenotfound.html
{% extends 'home/homeview.html' %} {% block meta_tags %} {% load static %}
<title>Page not Found</title>
{% endblock meta_tags %} {% block sideNav %}

{% if articles %}
<h3 id=""><a href="{% url 'frontview:sectionView' section %}">
    {{section}} JOB POSTS</a></h3>
<input type="text" id="SearchInput" onkeyup="SearchFunction()" placeholder="Search posts" id="myInput">
<ul id="sideNavUL">
    {% for article in articles %} 
    <li><a class="a" href="{% url 'frontview:articleView' article.id article.title_slug  %}">{{article}}</a></li>
     {% endfor %}
</ul>
{% else %}
<h3 id="">{{section}} Job Posts</h3>
<p>No vacancies at the moment</p>
{% endif %}
    

{% endblock sideNav %} {% block mainHeading %}
<div id="mainhead" class="mainhead">
    <h1 id="mainHeading">Post not found</h1>
</div>
{% endblock mainHeading %} {% block main %}
<article class="article">
    <p>The post you seek seems to be under review. Please, check back later.</p>
</article>
{% endblock main %} {% block ads %} {% endblock ads %} {% block mostviewed %}
{% if mostviewed %}
<h2>Most Viewed Job Posts</h2>
<div id="" class="articleInnerBox">

    {% for article in mostviewed %}
    <section class="articleDisplayBox">
        <h3><a href="{% url 'frontview:articleView' article.id article.title_slug %}">{{article}}</a></h3>
        <!-- {% if article.image %}
        <img class="" src="{{article.image.url}}" alt="{{article.image_description}}">{% endif %} -->
        <p>{{article.bodySnippet|safe}}</p>
        <p class="pub_date"> {{article.mod_date}}</p>
    </section>
    {% endfor %}
</div>
{% endif %} 
{% endblock mostviewed %} {% block news %}{% include './contactus.html' %} {% endblock news %}