application/urls.py
from django.urls import path
from . import views

app_name="applications"

urlpatterns = [
    path('<int:article_id>',views.applicationView,name='applications'),
    path('<int:app_id>/<str:action>',views.process_application,name='process'),
]

home/urls.py
from django.urls import path
from . import views

app_name="frontview"

urlpatterns = [
    path('',views.homeView,name='homeView'),
    path('hr',views.hrView,name='hrView'),
    path('legal',views.legalView,name='legalView'),
    path('about',views.aboutView,name='aboutView'),
    path('jobs/<str:section>',views.sectionView,name="sectionView"),
    path('<int:article_id>/<slug:article_slug>',views.articleView,name="articleView"),
]

login/urls.py
from django.urls import path
from .import views
from django.contrib.auth import views as auth_views


app_name="login"

urlpatterns = [
    path('',views.loginView,name="loginView"),
    path('logout',views.logoutView,name="logoutView"), 
   
    

   

]

publishers/urls.py
from django.urls import path
from . import views

app_name = "publisher"

urlpatterns = [
    path('', views.register, name="register"),
    path('editProfile', views.editProfile, name="editProfile"),
    path('editProfilePro', views.editProfilePro, name="editProfilePro"),
    path('<str:username>/articlecreate',
         views.ArticleCreateView, name="articleCreateView"),
    path('<str:username>/<int:article_id>/articlecreation',
         views.ArticleCreationView, name="articleCreationView"),
    path('<int:article_id>/<slug:article_slug>',
         views.articlePublisherView, name="articlePublisherView"),
    path('publish/<int:article_id>/<slug:article_slug>',
         views.publishView, name="publishView"),
    path('controlview/<int:sectionId>', views.controlView, name="controlView"),
    path('delete/<int:article_id>',
         views.articleDeleteView, name="articleDeleteView"),
    path('withdraw/<int:article_id>', views.articleWithdrawView,
         name="articleWithdrawView"),
    path('close/<int:article_id>/<str:action>', views.close_application,
         name="close"),
    path('<str:username>/<int:article_id>/editview',
         views.editView, name="editView"),
    path('<str:username>/<int:article_id>/editpro',
         views.editPro, name="editpro"),
    path('dashbord/<str:username>/<int:sectionId>/<str:action>',
         views.publisherView, name="publisherView"),
]

zinagohr/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path,include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('',include("home.urls"),name='home'),
    path('admin/', admin.site.urls),
    path('publisher/',include("publishers.urls")),
    path('applications/',include("application.urls")),
    path('login/',include("login.urls")),
    path('password_reset/',auth_views.PasswordResetView.as_view(template_name="login/passwordreset.html"),name='password_reset',),
    path('password_reset_done/',auth_views.PasswordResetView.as_view(template_name="login/password_reset_done.html"),name="password_reset_done",),
    path('password_reset_confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name="login/password_reset_confirm.html"), name='password_reset_confirm',),
    path( 'password_reset_completed/',auth_views.PasswordResetCompleteView.as_view(template_name="login/password_reset_complete.html"), name='password_reset_complete',),
]

urlpatterns+=staticfiles_urlpatterns()

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

publishers/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import pre_save, post_delete
from django.dispatch import receiver
# from django.utils import timezone
import datetime
import re
from PIL import Image
from math import floor
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile
import sys
# Create your models here.


class Section(models.Model):
    Name = models.CharField("Name", max_length=156)
    description = models.TextField(default="null", blank=False)

    def __str__(self):
        return self.Name

    class Meta:
        managed = True
        verbose_name = 'Section'
        verbose_name_plural = 'Sections'


class Publisher(models.Model):
    account = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name="Account")
    first_name = models.CharField("First Name", max_length=156)
    last_name = models.CharField("Last Name", max_length=156)
    verified = models.BooleanField(default=False)
    description = models.TextField("description", max_length=150, null=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    class Meta:
        managed = True
        verbose_name = 'Publisher'
        verbose_name_plural = 'Publishers'


class Article(models.Model):
    section = models.ForeignKey(Section, on_delete=models.CASCADE,related_name="section_article")
    title = models.CharField(max_length=255)
    title_slug = models.SlugField(default="null")
    description = models.TextField()
    keywords = models.CharField(max_length=255, default="null")
    image = models.ImageField(null=True,blank=True)
    image_source = models.CharField(max_length=255, null=True, blank=True)
    image_description = models.CharField(
        max_length=255, default='image', blank=True)
    sub_heading = models.CharField(max_length=255, null=True, blank=True)
    body_text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    mod_date = models.DateTimeField(null=True)
    publisher = models.ManyToManyField(Publisher)
    view_count = models.IntegerField(default=0)
    publish = models.BooleanField(default=False)
    still_open = models.BooleanField(default=True)

    def bodySnippet(self):
        body = self.body_text[:120]
        bodySnippet = re.sub(
            r"\s\w+$|(<strong>|</strong>|<em>|</em>|<b>|</b>|<i>|</i>|<u>|</u>|<a.+?>|</a>)", "", body)
        return f'{bodySnippet} ....'

    def __str__(self):
        return self.title

    class Meta:
        managed = True
        verbose_name = 'Article'
        verbose_name_plural = 'Articles'
        ordering = ['-pub_date']

    # def delete(self, *args, **kwargs):
    #     self.image.delete()
    #     super().delete(*args, **kwargs)

    def save(self, skip_md=True, *args, **kwargs):
        if skip_md:
            self.mod_date = datetime.datetime.now()
            
   

        if self.image:
            target_height = 333
            im = Image.open(self.image)
            width,height=im.size
            output = BytesIO()
            newHeight= target_height
            newWidth= int(newHeight/height*width)
            im = im.resize((newWidth,newHeight))
            im.save(output, format='JPEG', quality=100)
            output.seek(0)
            self.image = InMemoryUploadedFile(output, 'ImageField', "%s.jpg" % self.image.name.split(
                    '.')[0], 'image/jpeg', sys.getsizeof(output), None)

        super().save(*args, **kwargs)  # Call the real save() method


class Sections(models.Model):
    """Model definition for Sections."""
    # TODO: Define fields here
    article = models.ForeignKey(
        Article, related_name='sections', on_delete=models.CASCADE)
    sub_heading = models.CharField(max_length=255, null=True)
    Sub_section_image = models.ImageField(null=True, blank=True)
    image_source = models.CharField(max_length=255, null=True, blank=True)
    image_description = models.CharField(
        max_length=255, default="image", blank=True)
    body_text = models.TextField(null=True)

    class Meta:
        """Meta definition for Sections."""
        verbose_name = 'Sections'
        verbose_name_plural = 'Sections'

    def __str__(self):
        """Unicode representation of Sections."""
        return self.sub_heading

    def save(self, *args, **kwargs):
        if self.Sub_section_image:
            im = Image.open(self.Sub_section_image)
            width, height = im.size
            output = BytesIO()
            n = 0.5
            Width = floor(width * n)
            Height = floor(height * n)
            if width > 1000:
                im = im.resize((Width, Height))
                im.save(output, format='JPEG', quality=100)
                output.seek(0)
                self.Sub_section_image = InMemoryUploadedFile(output, 'ImageField', "%s.jpg" % self.Sub_section_image.name.split('.')[
                                                              0], 'image/jpeg', sys.getsizeof(output), None)

        super().save(*args, **kwargs)  # Call the real save() method

    # def delete(self, *args, **kwargs):
    #     self.Sub_section_image.delete()
    #     super().delete(*args, **kwargs)


@receiver(pre_save, sender=Article)
def delete_Artictle_image(sender, instance, *args, **kwargs):
    if instance.pk:
        article = Article.objects.get(pk=instance.pk)
        if article.image != instance.image:
            article.image.delete(False)


@receiver(pre_save, sender=Sections)
def delete_Sections_image(sender, instance, *args, **kwargs):
    if instance.pk:
        section = Sections.objects.get(pk=instance.pk)
        if section.Sub_section_image != instance.Sub_section_image:
            section.Sub_section_image.delete(False)


@receiver(post_delete, sender=Article)
def delete_artictle_image(sender, instance, using, *args, **kwargs):
    if instance.image:
        instance.image.delete(save=False)


@receiver(post_delete, sender=Sections)
def delete_sections_image(sender, instance, using, *args, **kwargs):
    if instance.Sub_section_image:
        instance.Sub_section_image.delete(save=False)

publishers/templates/publisher/articlePublisherView.html
{% extends 'publisher/register.html' %} {% block nav %}

<form action="{% url 'publisher:editView' user.username article.id %}" method="post">
    {% csrf_token %}
    <button type="submit">Edit</button>
</form>
<form action="{% url 'login:logoutView' %}" method="post">
    {% csrf_token %}
    <button type="submit">Sign Out</button>
</form>
{% endblock nav %} {% block main %}
<article class="article" style="margin-top: 135px">
    {% if messages %} {% for message in messages %}
    <p style="color: green">{{ message }}</p>
    {% endfor %} {% endif %}
    <h1 id="mainHeading" style="padding-bottom: 30px">{{article.title}}</h1>
    {% if article.image %}
    <figure class="">
        <img src="{{article.image.url}}" alt="">
        <figcaption><em>Image Source: {{article.image_source}}</em></figcaption>
    </figure>
    {% endif %}
    <section>
        {% if article.sub_heading %}
        <h2 class="">{{article.sub_heading}}</h2>
        {% endif %} {{article.body_text|safe}}
    </section>
    {% for section in sections %}
    <section>
        <h2>{{section.sub_heading}}</h2>
        {% if section.Sub_section_image %}
        <figure style="margin-bottom: 10px;" class="">
            <img src="{{section.Sub_section_image.url}}" alt="">
            <figcaption><em>Image Source: {{section.image_source}}</em></figcaption>
        </figure>{% endif %} {{section.body_text|safe}}
    </section>
    {% endfor %} 

    <p class="pub_date">Date of Publication: {{article.mod_date}}</p>

    <a target="blank" href="{% url 'frontview:articleView' article.id article.title_slug %}">VIEW IN MAIN SITE</a>
    {% if article.publish %}
    <form action="{% url 'publisher:articleWithdrawView' article.id %}" method="post">
        {% csrf_token %}
        <button class="submitButton publishButton" type="submit" onclick="return
            confirm('Are you sure you want to withdraw this article ?')">Withdraw</button>
    </form>
    
    {% else %} {% if form %} 
    <div class="publishbox">
        <form action="{% url 'publisher:publishView' article.id article.title_slug %}" method="post">
            {% csrf_token %} {{form}}
            <button class="submitButton publishButton" type="submit">Publish</button>
        </form>
    </div>
    {% endif %} {% endif %}
</article>
<script>
    hidePublishButton()

    function hidePublishButton() {
        let checkBox = document.querySelector("#id_publish")
        let button = document.querySelector(".publishButton")
        if (checkBox.checked) {
            button.disabled = false
            button.style.backgroundColor = "#0978c6"
        } else {
            button.disabled = true
            button.style.backgroundColor = "gray";
        }
        checkBox.addEventListener("change", () => {
            if (checkBox.checked) {
                button.disabled = false
                button.style.backgroundColor = "#0978c6"
            } else {
                button.disabled = true
                button.style.backgroundColor = "gray";
            }
        })

    }
</script>
{% endblock main %}

publishers/templates/publisher/controlview.html
{% extends 'publisher/register.html' %} {% block nav %}
<form action="{% url 'login:logoutView' %}" method="post">
    {% csrf_token %}
    <button type="submit">Sign Out</button>
</form>

{% endblock nav %} {% block main %}
<strong><p >{{section}}</p></strong> {% if article %}
<p style="padding:10px 20px 0px 10px">You have written {{article|length}} post{{article|pluralize}}.</p>
{% else %}
<p>You have not made any post in this section.</p>
{% endif %}

<ol class="list_items">
    {% for article in article %}
    <div class="items">
        <div class="innerItem">
            <li>
                <span><strong>{{article}}</strong></span>
            </li>
            <div class="buttons1">
                <form action="{% url 'publisher:editView' user.username article.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit">Edit</button>
                </form>
                <form action="{% url 'publisher:articlePublisherView' article.id article.title_slug %}" method="post">
                    {% csrf_token %}
                    <button type="submit">View</button>
                </form>

                <form action="{% url 'publisher:articleDeleteView' article.id  %}" method="post">
                    {% csrf_token %}
                    <button type="submit" onclick="return confirm('Are you sure you want to delete this article ?')">Delete</button>
                </form>
            </div>
            {% if article.publish and article.still_open %}
            <span style="margin:5px;">Published and still open</span>
            <div class="buttons2">
                <form action="{% url 'publisher:close' article.id 'close' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" onclick="return confirm('Are you sure you want to close this applications ?')">Close</button>
                </form>
                <form action="{% url 'applications:applications' article.id  %}" method="post">
                    {% csrf_token %}
                    <button type="submit">Applications</button>
                </form>
                <form action="{% url 'publisher:articleWithdrawView' article.id  %}" method="post">
                    {% csrf_token %}
                    <button type="submit" onclick="return confirm('Are you sure you want to withdraw this application ?')">Withdraw</button>
                </form>
            </div>
            {% elif article.publish and not article.still_open %}
            <span style="margin:5px;">Published and closed</span>
            <div class="buttons2">
                <form action="{% url 'publisher:close' article.id 'open' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" onclick="return confirm('Are you sure you want to open this applications ?')">Open</button>
                </form>
                <form action="{% url 'applications:applications' article.id  %}" method="post">
                    {% csrf_token %}
                    <button type="submit">Applications</button>
                </form>
                <form action="{% url 'publisher:articleWithdrawView' article.id  %}" method="post">
                    {% csrf_token %}
                    <button type="submit" onclick="return confirm('Are you sure you want to withdraw this application ?')">Withdraw</button>
                </form>
            </div>
            {% else %}
            <span>Unpublished</span> {% endif %}
        </div>
    </div>
    {% endfor %}
</ol>
{% endblock main %}

publishers/templates/publisher/editprofile.html
{% extends 'publisher/register.html' %} {% block nav %}
<form action="{% url 'login:logoutView' %}" method="post">
    {% csrf_token %}
    <button type="submit">Sign Out</button>
</form>
{% endblock nav %} {% block main %}
<strong><p> Welcome {{user.first_name}} {{user.last_name}}.</p></strong>
<form action="{% url 'publisher:editProfilePro'%}" method="post">
    <fieldset style="margin-top: 20px">
        <legend>UPDATE YOUR PROFILE</legend>
        {% csrf_token %} {% for field in userform %}
        <div class="formfield">
            {{field.errors}} {{field.label_tag}} {{field}} {% if field.help_text %}
            <p class="help">{{field.help_text|safe}}</p>
            {% endif %}
        </div>
        {% endfor %} {% for field in publisherform %}
        <div class="formfield">
            {{field.errors}} {{field.label_tag}} {{field}} {% if field.help_text %}
            <p class="help">{{field.help_text|safe}}</p>
            {% endif %}
        </div>
        {% endfor %}
        <ul id="extradata">
            <li>Describe yourself with a third person pronoun starting with your full name.</li>
            <li> It should not be more than 150 letters</li>
            {% comment %} <li>This will be displayed below all your articles</li>
            <li>You can add any of your social media handle</li> {% endcomment %}
        </ul>
        <input class="submitButton" type="submit" value="UPDATE">
    </fieldset>
</form>
{% endblock main %}

publishers/templates/publisher/editview.html
{% extends 'publisher/register.html' %} {% block nav %}
<form action="{% url 'login:logoutView' %}" method="post">
    {% csrf_token %}
    <button type="submit">Sign Out</button>
</form>
<form action="{% url 'publisher:articlePublisherView' article.id article.title_slug %}" method="post">
    {% csrf_token %}
    <button type="submit">View</button>
</form>
{% endblock nav %} {% block main %}
<div id="buttonDiv">
    <button type="button" data-command="bold" class="tool-btn"><img class="intLink" title="Bold"
            src="data:image/gif;base64,R0lGODlhFgAWAID/AMDAwAAAACH5BAEAAAAALAAAAAAWABYAQAInhI+pa+H9mJy0LhdgtrxzDG5WGFVk6aXqyk6Y9kXvKKNuLbb6zgMFADs=" />
    </button>
    <button type="button" data-command="insertUnorderedLIst" class="tool-btn"><img class="intLink" title="Bullet"
            src="data:image/gif;base64,R0lGODlhFgAWAMIGAAAAAB1ChF9vj1iE33mOrqezxv///////yH5BAEAAAcALAAAAAAWABYAAAMyeLrc/jDKSesppNhGRlBAKIZRERBbqm6YtnbfMY7lud64UwiuKnigGQliQuWOyKQykgAAOw==" />
    </button>
    <button type="button" data-command="insertOrderedList" class="tool-btn"><img class="intLink" title="Numbering"
            src="data:image/gif;base64,R0lGODlhFgAWAMIGAAAAADljwliE35GjuaezxtHa7P///////yH5BAEAAAcALAAAAAAWABYAAAM2eLrc/jDKSespwjoRFvggCBUBoTFBeq6QIAysQnRHaEOzyaZ07Lu9lUBnC0UGQU1K52s6n5oEADs=" />
    </button>
    <button type="button" data-command="justifyLeft" class="tool-btn"><img class="intLink" title="Left align"
            src="data:image/gif;base64,R0lGODlhFgAWAID/AMDAwAAAACH5BAEAAAAALAAAAAAWABYAQAIghI+py+0Po5y02ouz3jL4D4JMGELkGYxo+qzl4nKyXAAAOw==" />
    </button>
    <button type="button" data-command="justifyCenter" class="tool-btn"><img class="intLink" title="Center align"
            src="data:image/gif;base64,R0lGODlhFgAWAID/AMDAwAAAACH5BAEAAAAALAAAAAAWABYAQAIfhI+py+0Po5y02ouz3jL4D4JOGI7kaZ5Bqn4sycVbAQA7" />
    </button>
    <button type="button" data-command="justifyRight" class="tool-btn"><img class="intLink" title="Right align"
            src="data:image/gif;base64,R0lGODlhFgAWAID/AMDAwAAAACH5BAEAAAAALAAAAAAWABYAQAIghI+py+0Po5y02ouz3jL4D4JQGDLkGYxouqzl43JyVgAAOw==" />
    </button>
    <button type="button" data-command="italic" class="tool-btn"><img class="intLink" title="Italic"
            src="data:image/gif;base64,R0lGODlhFgAWAKEDAAAAAF9vj5WIbf///yH5BAEAAAMALAAAAAAWABYAAAIjnI+py+0Po5x0gXvruEKHrF2BB1YiCWgbMFIYpsbyTNd2UwAAOw==" />
    </button>
    <button type="button" data-command="underline" class="tool-btn"><img class="intLink" title="Underline"
            src="data:image/gif;base64,R0lGODlhFgAWAKECAAAAAF9vj////////yH5BAEAAAIALAAAAAAWABYAAAIrlI+py+0Po5zUgAsEzvEeL4Ea15EiJJ5PSqJmuwKBEKgxVuXWtun+DwxCCgA7" />
    </button>
    <button type="button" data-command="strikeThrough" class="tool-btn"><strong><strike>abc</strike></strong></button>
    <button type="button" data-command="subscript" class="tool-btn"><strong>X <sup><span
                    style="font-size: 10px">2</span></sup></strong> </button>
    <button type="button" data-command="superscript" class="tool-btn"><strong>X <sub><span
                    style="font-size: 10px">2</span></sub></strong> </button>
    <button type="button" data-command="createLInk" class="tool-btn">Add Link</button>
    <button type="button" data-command="unlink" class="tool-btn">UnLink</button>
    <button type="button" data-command="raisenumber" class="tool-btn">RaiseNum</button>
    <button type="button" data-command="removenumber" class="tool-btn">RemoveNum</button>
    <select id="heading">
        <option value="">Heading</option>
        <option value="h3">H3</option>
        <option value="h4">H4</option>
        <option value="h5">H5</option>
        <option value="h6">H6</option>
    </select>
</div>
<form style='margin-top:170px' action="{% url 'publisher:editpro' user.username article.id %}" enctype="multipart/form-data" method="post">
    <fieldset>
        <legend>UPDATE ARTICLE</legend>
        {% csrf_token %} {% for field in form %}
        <div class="formfield">
            {{field.errors}} {{field.label_tag}} {{field}} {% if field.help_text %}
            <p class="help">{{field.help_text|safe}}</p>
            {% endif %}
        </div>
        {% endfor %} {{sectionsForm.management_form}} {% for form in sectionsForm %}
        <div class="subsection">
            <h2>Article Sub Section</h2>
            {% for field in form %}
            <div class="formfield sub_section">
                {{field.errors}} {{field.label_tag}} {{field}}
            </div>
            {% endfor %}
        </div>
        {% endfor %}
        <div id="addsection">
        </div>
        {% for field in referenceForm %}
        <div class="formfield" id="end_notes">
            {{field.errors}} {{field.label_tag}} {{field}} {% if field.help_text %}
            <p class="help ">{{field.help_text|safe}}</p>
            {% endif %}
        </div>
        {% endfor %}

        <input class="submitButton" type="submit" onclick="return processData()" value="UPDATE">
    </fieldset>
</form>
<form action="javascript:void(0)" method="">
    {% csrf_token %}
    <button id='addSection' type="submit">Add Sub Section</button>
    <P style="display: none;" id='compare'>{{article.section}}</P>
</form>
{% endblock main %}

publishers/templates/publisher/publisherview.html
{% extends 'publisher/register.html' %} {% block nav %}
<form action="{% url 'publisher:editProfile' %}" method="post">
    {% csrf_token %}
    <button type="submit">Edit Profile</button>
</form>
<form action="{% url 'login:logoutView' %}" method="post">
    {% csrf_token %}
    <button type="submit">Sign Out</button>
</form>
{% endblock nav %} {% block main %} {% if messages %} {% for message in messages %}
<p style="color: green">{{ message }}</p>
{% endfor %} {% endif %}
    <p class="adminuser" style="margin-bottom: 20px;"> Welcome {{user.first_name}} {{user.last_name}}.</p>
<div class="flexView">
    <div class="sectionDiv flex_item1">
        <form action="{% url 'publisher:publisherView' user.username sectionId action %}" method="post">

            <legend>CREATE SECTION</legend>
            {% csrf_token %} {{form}}

            <button type="submit" class="submit submitButton">
        
        {% if action == "add" %}
            ADD
        {% else %}
            UPDATE
        {% endif %}
            
    </button>

        </form>

        <section class="list_items">
            {% for section in sections %}
            <div class="items">
                <div class="innerItem">
                    <p><a href="{% url 'publisher:controlView' section.id %}">{{section.Name}}</a></p>
                    <!-- <a class="delete" href="{% url 'publisher:publisherView' user.username section.id 'delete' %}">
                        <button> Delete</button>
                    </a> -->
                    <a href="{% url 'publisher:publisherView' user.username section.id 'edit' %}">
                        <button>
                    Edit
                    </button>
                    </a>
                </div>
            </div>
            {% endfor %}
        </section>
    </div>
    <form action="{% url 'publisher:articleCreateView' user.username %}" method="post" class="flex_item1">

        <legend>CREATE A NEW JOB POST</legend>
        {% csrf_token %} {% for field in article_form %}
        <div class="formfield">
            {{field.errors}} {{field.label_tag}} {{field}} {% if field.help_text %}
            <p class="help">{{field.help_text|safe}}</p>
            {% endif %}
        </div>
        {% endfor %}
        <input class="submitButton" type="submit" value="CREATE">

    </form>
</div>
{% endblock main %}

publishers/templates/publisher/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@400;500;700&family=Roboto:ital,wght@0,400;0,500;0,700;1,400;1,500;1,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/publishingdesign.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/fonts.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="shortcut icon" href="{% static 'css/img/logo.png' %}" type="image/png">
    <link rel="apple-touch-icon" href="{% static 'css/img/logo.png' %}">
    <link rel="icon" href="{% static 'css/img/logo.png' %}" type="image/png"> {% block title %}
    <title>Home | Zinago </title>
    {% endblock title %}
    <meta name="author" content="Emeka Casper Onwuepe " />
    <meta name="description" content="A Human Resource and legal firm dedicated to providing professional legal and HR Consulting Services and evolving Recruitment Solutions that help our customers become more productive and profitable." /> {% block keywords %}
    <meta name="keywords" content="Consulting, Human Resources, Recruitment,law firm, Abuja, Abuja law firm, Services" /> {% endblock keywords %}
    <meta name="author" content="Emeka Casper Onwuepe " />
    <meta property="og:url" content="{{request.build_absolute_uri}}" />
    <meta property="og:type" content="service" />
    <meta property="og:title" content="Zinago HR and Legal Services" />
    <meta property="og:description" content="A Human Resource firm dedicated to providing professional HR Consulting Services and evolving Recruitment Solutions that help our customers become more productive and profitable." />
</head>

<body>
    <div class="Bigwrapper">
        <header>
            <section class="menu">
                <div id="logo-div">
                        
                        {% if user.username %}
                        <a href="{% url 'publisher:publisherView' user.username 0 'view' %}">
                            <img class="logo" src="{% static 'css/img/logo.png' %}" alt="logo" width="100%">
                        </a>
                        {% else %}
                        <img class="logo" src="{% static 'css/img/logo.png' %}" alt="logo" width="100%">
                        {% endif %}
                </div>
                <nav id="nav" class="nav">
                    {% block nav %}
                    <form action="{% url 'login:logoutView' %}" method="post">
                        {% csrf_token %}
                        <button type="submit">LOGIN</button>
                    </form>
                    {% endblock nav %}
                </nav>
            </section>
        </header>
        <main>
            {% block main %}
            <fieldset style="margin-top:150px">
                <legend>REGISTER AS A PUBLISHER</legend>
                <form action="{% url 'publisher:register' %}" method="post">
                    {% csrf_token %} {% for field in form %}
                    <div class="formfield">
                        {{field.errors}} {{field.label_tag}} {{field}} {% if field.help_text %}
                        <p class="help">{{field.help_text|safe}}</p>
                        {% endif %}
                    </div>
                    {% endfor %}
                    <div id="extradata">
                        <label for="section" style="display: block;padding-top:5px">Select Section</label>
                        <select name="section" id="section">
                            <option value="">-----------</option>
                            {% for section in sections  %}
                            <option value="{{section.id}}">{{section}}</option>
                            {% endfor %}
                        </select>
                        <label for="description" style="display: block;padding-top:5px">Describe Yourself</label>
                        <textarea name="description" maxlength="150" id="" cols="" rows="3" required></textarea>
                        <ul>
                            <li>Describe yourself with a third person pronoun starting with your full name.</li>
                            <li> It should not be more than 150 letters</li>
                            <li>This will be displayed below all your articles</li>
                            <li>You can add any of your social media handle</li>
                        </ul>
                    </div>

                    <input class="submitButton" type="submit" value="SIGN UP">
                </form>
            </fieldset>
            {% endblock main %}
        </main>

        <div id="backToTop" class="backToTop">
            <a href="#">&#10094;</a>
        </div>

        {% block footer %}
        <footer>
            <p id="footer"> Copyright &copy; <span id="footerdate" style="padding: 0%"></span>. All rights reserved. zinago.ng <br /> </p>
        </footer>
        {% endblock footer %}

    </div>
    <script src="{% static 'javascript/publishingview.js' %}"></script>
</body>

</html>