application/urls.py
from django.urls import path
from . import views

app_name="applications"

urlpatterns = [
    path('<int:article_id>',views.applicationView,name='applications'),
    path('<int:app_id>/<str:action>',views.process_application,name='process'),
]

home/urls.py
from django.urls import path
from . import views

app_name="frontview"

urlpatterns = [
    path('',views.homeView,name='homeView'),
    path('hr',views.hrView,name='hrView'),
    path('legal',views.legalView,name='legalView'),
    path('about',views.aboutView,name='aboutView'),
    path('jobs/<str:section>',views.sectionView,name="sectionView"),
    path('<int:article_id>/<slug:article_slug>',views.articleView,name="articleView"),
]

login/urls.py
from django.urls import path
from .import views
from django.contrib.auth import views as auth_views


app_name="login"

urlpatterns = [
    path('',views.loginView,name="loginView"),
    path('logout',views.logoutView,name="logoutView"), 
   
    

   

]

zinagohr/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path,include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('',include("home.urls"),name='home'),
    path('admin/', admin.site.urls),
    path('publisher/',include("publishers.urls")),
    path('applications/',include("application.urls")),
    path('login/',include("login.urls")),
    path('password_reset/',auth_views.PasswordResetView.as_view(template_name="login/passwordreset.html"),name='password_reset',),
    path('password_reset_done/',auth_views.PasswordResetView.as_view(template_name="login/password_reset_done.html"),name="password_reset_done",),
    path('password_reset_confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name="login/password_reset_confirm.html"), name='password_reset_confirm',),
    path( 'password_reset_completed/',auth_views.PasswordResetCompleteView.as_view(template_name="login/password_reset_complete.html"), name='password_reset_complete',),
]

urlpatterns+=staticfiles_urlpatterns()

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

application/models.py
from django.db import models
from publishers.models import Article

# Create your models here.
class Application(models.Model):
    """Model definition for Application."""
    job = models.ForeignKey(Article, verbose_name="post", 
                            on_delete=models.CASCADE,related_name="post_applications")
    full_name = models.CharField("full_name", max_length=100)
    email = models.EmailField("email", max_length=50)
    phone_number = models.CharField('phone_number', max_length=50)
    address = models.CharField('address', max_length=256)
    evelator_speech = models.TextField('evelator_speech')
    cv = models.FileField("cv")
    selected = models.BooleanField("selected",default=False)
    employed = models.BooleanField("employed",default=False)

    # TODO: Define fields here

    class Meta:
        """Meta definition for Application."""

        verbose_name = 'Application'
        verbose_name_plural = 'Applications'

    def __str__(self):
        """Unicode representation of Application."""
        return f"{self.full_name} {self.phone_number}"

application/views.py
from django.shortcuts import render, reverse
from django.http import  HttpResponseRedirect
from django.contrib.auth.decorators import login_required

from publishers.models import Article, Publisher
from .models import Application
# Create your views here.
@login_required(login_url="login:loginView")
def applicationView(request, article_id):
    post = None
    try: 
        post = Article.objects.get(id=article_id)
    except Article.DoesNotExist:
        return HttpResponseRedirect(reverse("publisher:publisherView",
        kwargs={"username":request.user.username,"sectionId":0,"action":"add"}))
    applications = post.post_applications.filter(selected=False)
    selected = post.post_applications.filter(selected=True)
    total = len(applications) + len(selected)
    publisher = Publisher.objects.get(account=request.user)
    return render(request, "application/applications.html", {'post':post,'publisher':publisher,
                                                            "applications":applications,"total":total,
                                                            'selected':selected
                                                            })
    
@login_required(login_url="login:loginView")
def process_application(request,app_id,action):
    application = None
    
    try: 
            application = Application.objects.get(id=app_id)
    except Application.DoesNotExist:
            return HttpResponseRedirect(reverse("publisher:publisherView",
            kwargs={"username":request.user.username,"sectionId":0,"action":"add"}))
    
    if action == "select":
        application.selected = True
        application.save()
    
    if action == "unselect":
        application.selected = False
        application.save()
        
    if action == "employed":
        application.employed = True
        application.save() 
        
    return HttpResponseRedirect(reverse('applications:applications',
                                                kwargs={"article_id":application.job_id}))

application/templates/application/applications.html
{% extends 'publisher/register.html' %} {% block nav %}
<form action="{% url 'login:logoutView' %}" method="post">
    {% csrf_token %}
    <button type="submit">Sign Out</button>
</form>

{% endblock nav %} {% block main %}
<h1 style="margin-top: 125px">{{post}}</h1> {% if total %}
<p style="padding:10px 20px 0px 10px">You have recieved {{total}} application{{total|pluralize}}. {{selected|length}} selected</p>
{% else %}
<p>This Job Posting has not recieved any application yet.</p>
{% endif %}

<section class='applications list_items'>
    {% for application in applications %}
    <div class="items">
        <div class="innerItem">
            <div>
                <p>{{application.evelator_speech}}</p>
            </div>
            <div class='details'>
                <p><strong>Name:</strong> {{application.full_name}}</p>
                <p><strong>Email:</strong> {{application.email}}</p>
                <p><strong>Phone Number:</strong> {{application.phone_number}}</p>
                <p><strong>Address:</strong> {{application.address}}</p>
                <p><a target="_blank" href="{{application.cv.url}}">View CV</a></p>
                <a href="{% url 'applications:process' application.id 'select' %}"><button>Select</button></a>
            </div>
        </div>
    </div>
    {% endfor %}
</section>

{% if selected %}
<div class="tablecontainer">
    <table>
        <thead>
            <tr>
                <th colspan="7">SELECTED</th>
            </tr>
            <tr>
                <th>S/N</th>
                <th>Name</th>
                <th>Email</th>
                <th>Phone Number</th>
                <th>CV</th>
                <th>Unselect</th>
                <th>Employ</th>
            </tr>
        </thead>
        <tbody>

            {% for application in selected %}
            <tr>
                <td>{{forloop.counter}}</td>
                <td> {{application.full_name}}</td>
                <td>{{application.email}}</td>
                <td>{{application.phone_number}}</td>
                <td><a target="_blank" href="{{application.cv.url}}">View CV</a></td>
                {% if application.employed %}
                <td></td>
                <td> <strong>Employed</strong> </td>
                {% else %}
                <td><a href="{% url 'applications:process' application.id 'unselect' %}"><button>Unselect</button></a></td>
                <td><a href="{% url 'applications:process' application.id 'employed' %}"><button>Employed</button></a></td> {% endif %}

            </tr>

            {% endfor %}


        </tbody>
    </table>
</div>
{% endif %} {% endblock main %}